# version: "3.9"
# services: 
#   postgres:
#     container_name: postgredb
#     image: postgres:latest
#     restart: always
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     volumes:
#       - postgres:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#     volumes:
#       - ./sql/setup.sql:/docker-entrypoint-initdb.d/init.sql

# pgadmin:
#     container_name: pgadmin4_container
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"

version: '3.9'
services:
  db:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"